# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: create venv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: cache virtual environment for later jobs.
      - save_cache:
          key: venv-cache
          paths:
            - venv

  test:
    docker:
      - image: circleci/python:3.8
      # Step 4: restore virtual environment from cache, run tests
    steps :
      - checkout
      - restore_cache:
          key: venv-cache
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -v --cov

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build